from temp import *
from vetr import *
from da import *


temp = [
    {
        'temp_spb': str(int(tem_spb)) + '°C',
        'temp_msk': str(int(tem_msk)) + '°C',
        'temp_don': str(int(tem_don)) + '°C',
        'temp_spb1': str(int(tem_spb)),
        'temp_msk1': str(int(tem_msk)),
        'temp_don1': str(int(tem_don)),
        # 'weather_today1': str(sweather_today[0]),
        # 'weather_today2': str(sweather_today[1]),
        # 'weather_today3': str(sweather_today[2]),
        # 'weather_today4': str(sweather_today[3]),
        # 'weather_today5': str(sweather_today[4]),
        # 'weather_today6': str(sweather_today[5]),
        # 'weather_today7': str(sweather_today[6]),
        # 'weather_today8': str(sweather_today[7]),
        'weather_tomorrow1': str(sweather_tomorrow),
        'weather_tomorrow2': str(sweather_tomorrow1),
        'weather_tomorrow3': str(sweather_tomorrow2),
        'weather_tomorrow4': str(sweather_tomorrow3),
        'weather_tomorrow5': str(sweather_tomorrow4),
        'weather_tomorrow6': str(sweather_tomorrow5),
        'weather_tomorrow7': str(sweather_tomorrow6),
        'weather_tomorrow8': str(sweather_tomorrow7),

        # 'mweather_today1': str(mweather_today[0]),
        # 'mweather_today2': str(mweather_today[1]),
        # 'mweather_today3': str(mweather_today[2]),
        # 'mweather_today4': str(mweather_today[3]),
        # 'mweather_today5': str(mweather_today[4]),
        # 'mweather_today6': str(mweather_today[5]),
        # 'mweather_today7': str(mweather_today[6]),
        # 'mweather_today8': str(mweather_today[7]),
        'mweather_tomorrow1': str(mweather_tomorrow),
        'mweather_tomorrow2': str(mweather_tomorrow1),
        'mweather_tomorrow3': str(mweather_tomorrow2),
        'mweather_tomorrow4': str(mweather_tomorrow3),
        'mweather_tomorrow5': str(mweather_tomorrow4),
        'mweather_tomorrow6': str(mweather_tomorrow5),
        'mweather_tomorrow7': str(mweather_tomorrow6),
        'mweather_tomorrow8': str(mweather_tomorrow7),

        # 'dweather_today1': str(dweather_today[0]),
        # 'dweather_today2': str(dweather_today[1]),
        # 'dweather_today3': str(dweather_today[2]),
        # 'dweather_today4': str(dweather_today[3]),
        # 'dweather_today5': str(dweather_today[4]),
        # 'dweather_today6': str(dweather_today[5]),
        # 'dweather_today7': str(dweather_today[6]),
        # 'dweather_today8': str(dweather_today[7]),
        'dweather_tomorrow1': str(dweather_tomorrow),
        'dweather_tomorrow2': str(dweather_tomorrow1),
        'dweather_tomorrow3': str(dweather_tomorrow2),
        'dweather_tomorrow4': str(dweather_tomorrow3),
        'dweather_tomorrow5': str(dweather_tomorrow4),
        'dweather_tomorrow6': str(dweather_tomorrow5),
        'dweather_tomorrow7': str(dweather_tomorrow6),
        'dweather_tomorrow8': str(dweather_tomorrow7),
        'v_spb': str(int(v_spb)) + ' м/c',
        'v_msk': str(int(v_msk)) + ' м/c',
        'v_don': str(int(v_don)) + ' м/c',
        'd_spb': str(int(int(d_spb) * 0.75)) + ' мм рт. ст.',
        'd_msk': str(int(int(d_msk) * 0.75)) + ' мм рт. ст.',
        'd_don': str(int(int(d_don) * 0.75)) + ' мм рт. ст.'
    }
]
pass