from temp import *
from vetr import *
from da import *


temp = [
    {
        'temp_spb': str(int(tem_spb)) + '°C',
        'temp_msk': str(int(tem_msk)) + '°C',
        'temp_don': str(int(tem_don)) + '°C',
        'temp_kro': str(int(tem_kro)) + '°C',
        'temp_spb1': str(int(tem_spb)),
        'temp_msk1': str(int(tem_msk)),
        'temp_don1': str(int(tem_don)),
        'temp_kro1': str(int(tem_kro)),
        'weather1': str(sweather),
        'weather2': str(sweather1),
        'weather3': str(sweather2),
        'weather4': str(sweather3),
        'weather5': str(sweather4),
        'weather6': str(sweather5),
        'weather7': str(sweather6),
        'weather8': str(sweather7),
        'mweather1': str(mweather),
        'mweather2': str(mweather1),
        'mweather3': str(mweather2),
        'mweather4': str(mweather3),
        'mweather5': str(mweather4),
        'mweather6': str(mweather5),
        'mweather7': str(mweather6),
        'mweather8': str(mweather7),
        'dweather1': str(dweather),
        'dweather2': str(dweather1),
        'dweather3': str(dweather2),
        'dweather4': str(dweather3),
        'dweather5': str(dweather4),
        'dweather6': str(dweather5),
        'dweather7': str(dweather6),
        'dweather8': str(dweather7),
        'kweather1': str(kweather),
        'kweather2': str(kweather1),
        'kweather3': str(kweather2),
        'kweather4': str(kweather3),
        'kweather5': str(kweather4),
        'kweather6': str(kweather5),
        'kweather7': str(kweather6),
        'kweather8': str(kweather7),
        'v_spb': str(int(v_spb)) + ' м/c',
        'v_msk': str(int(v_msk)) + ' м/c',
        'v_don': str(int(v_don)) + ' м/c',
        'v_kro': str(int(v_kro)) + ' м/c',
        'd_spb': str(int(int(d_spb) * 0.75)) + ' мм рт. ст.',
        'd_msk': str(int(int(d_msk) * 0.75)) + ' мм рт. ст.',
        'd_don': str(int(int(d_don) * 0.75)) + ' мм рт. ст.',
        'd_kro': str(int(int(d_kro) * 0.75)) + ' мм рт. ст.'
    }
]